// <auto-generated />
using System;
using DB_Context_Library;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DB_Context_Library.Migrations
{
    [DbContext(typeof(BugCentreContext))]
    partial class BugCentreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Entities_Library.Bug", b =>
                {
                    b.Property<int>("BugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BugName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BugPriorityPriorityID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeReported")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.HasKey("BugID");

                    b.HasIndex("BugPriorityPriorityID");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("Entities_Library.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BugID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteText")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId");

                    b.HasIndex("BugID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Entities_Library.Priority", b =>
                {
                    b.Property<int>("PriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriorityName")
                        .HasColumnType("TEXT");

                    b.HasKey("PriorityID");

                    b.ToTable("Priority");
                });

            modelBuilder.Entity("Entities_Library.Bug", b =>
                {
                    b.HasOne("Entities_Library.Priority", "BugPriority")
                        .WithMany()
                        .HasForeignKey("BugPriorityPriorityID");
                });

            modelBuilder.Entity("Entities_Library.Note", b =>
                {
                    b.HasOne("Entities_Library.Bug", "Bug")
                        .WithMany("Notes")
                        .HasForeignKey("BugID");
                });
#pragma warning restore 612, 618
        }
    }
}
