// <auto-generated />
using System;
using BugCentre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugCentre.Migrations
{
    [DbContext(typeof(BugCentreContext))]
    [Migration("20191231153959_BugsTable")]
    partial class BugsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Bug", b =>
                {
                    b.Property<int>("BugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeReported")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("BugID");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BugID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId");

                    b.HasIndex("BugID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Note", b =>
                {
                    b.HasOne("Bug", "Bug")
                        .WithMany("Notes")
                        .HasForeignKey("BugID");
                });
#pragma warning restore 612, 618
        }
    }
}
